#!/bin/bash

echo REACT_APP_STATE_API_URL=$REACT_APP_STATE_API_URL >> .env
echo REACT_APP_STATE_APPLICATION_ID=$REACT_APP_STATE_APPLICATION_ID >> .env
echo REACT_APP_STATE_REST_API_KEY=$REACT_APP_STATE_REST_API_KEY >> .env